### ISSUE TITLE
Question about the input of the model, how to extract ROI features

### ISSUE THREAD

**Issue by emma-sjwang** [Meiyan88/MCNET#1]
Dear Authors,

Thank you very much for sharing this wonderful work!
I am really interested in the AD prediction task and would like to discuss it more with you.
I have learned a lot from your released arxiv paper and partial codes.

As shown in the paper, the data imputation is conducted on the MRI and PET ROI features.
May I know how to extract such ROI features before the whole processing? What is the size of ROI feature?

Moreover, figure 3 is quite amazing! I love it so much.
Would you mind sharing how I can draw a figure like this?

Thank you very much in advance for your help!

Best,

**Comment by Meiyan88** [comment]
For MRI data, region of interest (ROI) based features were extracted under the following preprocessing steps: (a) anterior commissure-posterior commissure correction with MIPAV software (https://mipav.cit.nih.gov/); (b) image intensity inhomogeneity correction by applying N3 algorithm; (c) skull stripping via HD-BET (https://github.com/MIC-DKFZ/HD-BET); (d) registering images to Montreal Neurological Institute (MNI) space via advanced normalization tools (ANTs) (https://github.com/ANTsX/ANTsPy); (e) three main tissues (i.e., gray matter (GM), white matter, and cerebrospinal fluid) segmentation using Atropos algorithm in ANTs; (f) applying the automated anatomical label (AAL) atlas of MNI space to project 90 brain ROIs; and (g) computing GM tissue volume of each ROI in the MNI space. For PET images, the co-registration strategy was utilized to align them to the corresponding MRI images via ANTs and the average intensity of each ROI was calculated as its feature. Finally, 90-dimensional ROI-based were separately extracted from the MRI and PET data for each subject.

Figure 3 was obtained through the BrainNetViewer tool, and I have attached their website: https://www.nitrc.org/projects/bnv/
